version: "3"
services:
  notebook:
    # image: jupyter/datascience-notebook
    image: jupyter/datascience-notebook/latex
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
